version: '3.9'

services:
  mongo1:
    container_name: mongo1
    image: mongo:latest
    volumes:
      - ~/mongors/data1:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - mongors-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=prisma
      - MONGO_INITDB_ROOT_PASSWORD=abcd1234
      # - REPLICA_SET_NAME=myRepl
    ports:
      - 27021:27017
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs"]
  mongo2:
    container_name: mongo2
    image: mongo:latest
    volumes:
      - ~/mongors/data2:/data/db
    networks:
      - mongors-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=prisma
      - MONGO_INITDB_ROOT_PASSWORD=abcd1234 
      # - REPLICA_SET_NAME=myRepl
    ports:
      - 27022:27017
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs"]
  mongo3:
    container_name: mongo3
    image: mongo:latest
    volumes:
      - ~/mongors/data3:/data/db
    networks:
      - mongors-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=prisma
      - MONGO_INITDB_ROOT_PASSWORD=abcd1234
      # - REPLICA_SET_NAME=myRepl
    ports:
      - 27023:27017
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs"]

networks:
  mongors-network:
    driver: bridge